### ISSUE TITLE
rolcatupdate removed in postgresql 9.5

### ISSUE THREAD

**Issue by soleuu** [dalibo/pgsnap#5]
Hello,
pgsnap 0.9 not working on postgresql 9.5
commenting the column rolcatupdate in the query make it work. as it have been removed in 9.5

file : lib/roles.php

**Comment by gleu** [comment]
You're right. This has been fixed last year (see 114e3d9c), but I guess that means we need to push out a new release.

**Comment by gleu** [comment]
New release available: https://github.com/dalibo/pgsnap/archive/REL_0_10_0.tar.gz
